### ISSUE TITLE
Weekly Scrum 03/15/18

### ISSUE THREAD

**Issue by keeganwills** [Apocahub/4806Project#16]

**Comment by keeganwills** [comment]
I created testing for the databases and fixed a bug that duplicated every user multiple times in the DB. Next week i will complete the ORM diagram, continue to update the UML, and keeps adding Unit tests as needed.

**Comment by Apocahub** [comment]
I updates the login page and implemented verification of user sessionId through cookies. I will be continuing to refine the authentication process as well as tying it into the repos as they are further implemented

**Comment by Samadroberts** [comment]
This week I helped groom the backlog, and added verification of logged in users using their current cookie session. I worked on maintaining a clean code base and added the implementation which allows professors to view their current projects as well as create new projects.

The obstacles holding me back are limited to completing 4th year project, and other class projects

**Comment by wardandr576** [comment]
This week I helped implement the verification and login controller. I worked on implementation for the demo and helped with adding CSS to landing pages . 
The obstacles holding me back are studying for a 40% final next week and fourth year engineering project
