### ISSUE TITLE
Weekly Scrum 3/22/18

### ISSUE THREAD

**Issue by Apocahub** [Apocahub/4806Project#45]

**Comment by Samadroberts** [comment]
I implemented a delete button for professors to delete their projects. I added basic framework for integration testing.

Obstacles include tests and projects upcoming in other classes.

**Comment by keeganwills** [comment]
I updated the UML diagram, fixed a few Unit tests, and added the ORM diagram.
Next week i will continue to update diagrams and unit tests, as well as complete more integration testing.

**Comment by Apocahub** [comment]
I implemented cookie validation, updated table rendering, unified endpoints, and logout functionality. This next week we will be finalizing the project, by adding scheduling, fixing project restrictions, and adding to integration tests.

**Comment by wardandr576** [comment]
I helped implemented the features that are currently working with Conlan, I will help implement more features and add integration tests.
